[package]
name = "zjhttpc"
version = "0.1.0"
edition = "2024"

[dependencies]
async-std = "1.13.0"
base64-simd = "0.8.0"
hashbrown = "0.15.2"
nom = "8.0.0"
rustls = { version = "0.23.23", features = ["hashbrown"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
thiserror-context = "0.1.2"
url = "2.5.4"
